### ISSUE TITLE
determine facet order

### ISSUE THREAD

**Issue by malantonio** [LafayetteCollegeLibraries/spot#193]
honestly, i chose the current order on the fly and have just stuck with it.

**Comment by noraegloff** [comment]
It looks like facets for _Resource Type_, _Physical Medium_, _Language_, _Division_, _Organization_, and _Subject_ are in the model but are missing from the dev site.  For Subject I'm guessing it's because none of the incoming metadata had values in the Subject property, but what about the others? 

I like having the _Year_ facet at the bottom, because of the slider. I would probably group the facets this way, leaving the two Admin facets where they are at the bottom: 

Collection
Resource Type
Publisher
Organization
Division
Academic Department
Subject
Keyword
Language
Location
Year
