### ISSUE TITLE
add ldr collections to config/collections.yml

### ISSUE THREAD

**Issue by malantonio** [LafayetteCollegeLibraries/spot#200]
we should have collections for:

- [x] faculty publications
- [x] bytes and books
- [x] gazette of american friends of lafayette
- [ ] course catalogs
- [ ] college administration
- [ ] public safety

more?

**Comment by malantonio** [comment]
most of these are here: https://github.com/LafayetteCollegeLibraries/spot/blob/239e559/config/collections.yml#L33-L40

still need to decide about course catalogs / college reports

**Comment by noraegloff** [comment]
What about **College Administration** (contains former Communications, Development, Facility Planning and Construction, Finance and Administration, Office of Institutional Research, Office of Student Development, Office of the Registrar, Parent Relations, President’s Office, Provost’s Office) instead of "College Reports"? 

**Course Catalogs**

+ **Public Safety**
