### ISSUE TITLE
add notes field to publication?

### ISSUE THREAD

**Issue by malantonio** [LafayetteCollegeLibraries/spot#213]
i hate to keep tinkering with the metadata model for publications, but i'm not entirely sure the description field should be where the notes land. this throws me for a loop every time i see it:

![Screen Shot 2019-04-24 at 10 28 19 AM](https://user-images.githubusercontent.com/2744987/56667414-c6925480-667b-11e9-88ea-5030bac292c9.png)

thoughts @noraegloff?

**Comment by noraegloff** [comment]
For the incoming Magazine MODS data with these errata statements, I agree it that the outcome of mapping Note to Description is looking sort of ugly and confusing.  Since the style of the incoming MODS for many of these is a sentence containing a semicolon, it has been ingested as 2 values - which makes matters worse.  

One solution could be for me to remediate the incoming data for this property to remove the semicolon, so that it wouldn't be confusingly split up into two separate values. 

A more effective solution might be for me to see the writing on the wall here, break down, and add a Note property to the model. This sort of background information / bibliographic oddity really typifies the spirit of the Note property. What do you think?

**Comment by noraegloff** [comment]
bump @malantonio

**Comment by malantonio** [comment]
my vote would be for the latter option -- adding a note property. my comment about being thrown for a loop was more re: the note being in the description rather than the out-of-order split.

**Comment by malantonio** [comment]
from the model document:

> **Property Label:** Note
> **Schema Mapping:** skos:note
> **Expected Value or Range - Controlled Source/Vocab:** Free text terms.
> **Expected Value or Range - Data Type:** xsd:string (Literal)
> **Namespace Definition:** Use for the note value.
> **Obligation:** {0,n}
> **Usage Notes:** This property will not be visible to puiblic users, only to internal users.  To be used for any information important to internal maintenance of records or relevant to the original items, such as administrative, digitization, or decision documentation.
> **Source:** Map from <Note> in Lafayette Magazine MODS data.  Map from <note> in Shakespeare Bulletin Collection MODS data.
> **Remediation Notes:** n/a
> **Facetable?:** no
> **In Hyrax Core or Basic Metadata?:** no
