### ISSUE TITLE
add ux to copy permalink to item on catalog#index

### ISSUE THREAD

**Issue by malantonio** [LafayetteCollegeLibraries/spot#268]
this has been asked for _a lot_ by our stakeholders and i keep forgetting to make an issue for it. there's a desire to have a clear way to copy the url for an item at the catalog results view. this can probably be a third-party widget like [clipboard.js](https://github.com/zenorocha/clipboard.js/)?

**Comment by malantonio** [comment]
i'd prefer to use the handle urls as the value that's being copied, but i wonder if the `hdl.handle.net` url will throw some people off as it's not a lafayette url?

**Comment by noraegloff** [comment]
I think that labeling the handle.net URLs with some sort of label e.g. "permalink" in the catalog results view, right below Date Issued, would prevent any confusion for users (see screenshot).  I agree with you that we should absolutely be serving up the handle.net URLs for this. 
![Screen Shot 2019-08-29 at 11 57 10 AM](https://user-images.githubusercontent.com/38009796/63957003-9574c700-ca55-11e9-9210-8f65083ac5fd.jpg)

Which brings up two thoughts... 
     1. This is going to involve making handle.net URLs for virtually all of the resources in the repo, many of which currently don't have them. Am I correct here? 
     2. In the old repository, the handle.net URL / permalink was printed right in the item record. 
![Screen Shot 2019-08-29 at 12 06 09 PM](https://user-images.githubusercontent.com/38009796/63957100-c48b3880-ca55-11e9-8c8c-f4660ca3a5f8.png)
But in the new repository that isn't the case (although the Handle ID, which was stored as metadata, is being displayed). I think there is a good case for displaying the handle.net URL right in the record so that it's easy for users to copy/paste and users are encouraged to use a permalink whenever they are citing the resource.

**Comment by malantonio** [comment]
> 1. This is going to involve making handle.net URLs for virtually all of the resources in the repo, many of which currently don't have them. Am I correct here?

yeah, the plan is to mint a handle URI for every item that gets ingested. so this'll lead some to have two working URIs (retaining our older URIs for legacy reasons). but the handle URI we'll display will always be the newer one (which'll look like `http://hdl.handle.net/<prefix>/<noid>`)
