### ISSUE TITLE
expand collection landing page

### ISSUE THREAD

**Issue by malantonio** [LafayetteCollegeLibraries/spot#270]
we expanded the collection metadata a few months ago (see bd906553ee among others) + maybe we should take a little time to update the ui for them?

**Comment by noraegloff** [comment]
This is a good idea! Right now the individual Collection pages are very sparse.  

In terms of Collections pages in other Hyrax implementations, Northwestern has a very simple (I think it's just the default?) view but I like the way that information about the collection is presented - giving the extent (number and size of items in the collection), uploader, subjects, collection permanent URL. I like that there is a breadcrumb at the top to take the user back to their original search results.  

<img width="1180" alt="northwestern_coll" src="https://user-images.githubusercontent.com/38009796/64564401-7280c780-d31f-11e9-831d-4af777b7bbcc.png">

UCLA Collection pages have a slightly customized presentation of Collection level metadata that I think adds some value for the user but I would like to hear your thoughts.  The general collection description, date range, and physical repository info are at the top of an individual collection page, and then there are tabs for browsing items, viewing additional collection level metadata, contact info, and info about where to find the physical items. I like this strategy because it gives the user the option to view a lot of info about a collection, but that info is broken up logically and also doesn't crowd the page because it is broken up across a few tabs. 

<img width="1647" alt="ucla_coll1" src="https://user-images.githubusercontent.com/38009796/64564418-7dd3f300-d31f-11e9-952a-c359a2982acf.png">

<img width="1251" alt="ucla_coll2" src="https://user-images.githubusercontent.com/38009796/64564521-b96ebd00-d31f-11e9-9e31-06acf273193f.png">

<img width="1229" alt="Screen Shot 2019-09-09 at 4 34 02 PM" src="https://user-images.githubusercontent.com/38009796/64564535-c4295200-d31f-11e9-9b94-bccb91293c35.png">
