### ISSUE TITLE
drop date_available from the publication form?

### ISSUE THREAD

**Issue by malantonio** [LafayetteCollegeLibraries/spot#352]
just the form! we'll keep the field in the object model, but maybe we don't need the field to be editable because:

- ~this gets filled in by hyrax automatically on creation~ (turns out i'm wrong about this, but it's something we can use the actor stack for)
- the migration scripts will change the date if available in the metadata
  - should take care of back-dating old items

need to look into how hyrax handles dating embargoed items: do we want the `date_available` to be when it was initially added to repo or when the embargo is up?

@noraegloff thoughts?

**Comment by noraegloff** [comment]
@malantonio I'm comfortable with leaving this off the form.  It does seem redundant to have it in the form below Date Issued, since if a user selects the radio button for Embargo in the Visibility section, they will be prompted to enter essentially the same date information there as well. 

[DCMI](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#terms-available) defines dct:available as "Date (often a range) that the resource became or will become available." 
 I think date_available should contain date information about when the embargo is over IF the work had an embargo on it. For works that don't have an embargo, I suppose it would be the datetime of ingest.  Does that feel too redundant to you?
